"""
Flask server for "Visualizing the Hidden Activity of Artificial Neural Networks".
Serves the D3 visualization (T1: inter-epoch, T2: inter-layer) and the precomputed
projection data generated by gen/generate_data.py.

Run:  python app.py    then open http://127.0.0.1:5000
"""
import os
from flask import Flask, render_template, jsonify, send_from_directory

app = Flask(__name__)
DATA_DIR = os.path.join(app.root_path, "static", "data")

DATASETS = ["mnist", "svhn", "cifar10"]


@app.route("/")
def index():
    available = [d for d in DATASETS
                 if os.path.exists(os.path.join(DATA_DIR, f"{d}_meta.json"))]
    return render_template("index.html", datasets=available)


@app.route("/data/<path:fname>")
def data(fname):
    return send_from_directory(DATA_DIR, fname)


if __name__ == "__main__":
    app.run(debug=True, port=5000)
